# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/felix/Software/Bausätze/Tetris

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/felix/Software/Bausätze/Tetris

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/felix/Software/Bausätze/Tetris/CMakeFiles /home/felix/Software/Bausätze/Tetris/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/felix/Software/Bausätze/Tetris/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named get_calibration

# Build rule for target.
get_calibration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_calibration
.PHONY : get_calibration

# fast build rule for target.
get_calibration/fast:
	$(MAKE) -f CMakeFiles/get_calibration.dir/build.make CMakeFiles/get_calibration.dir/build
.PHONY : get_calibration/fast

#=============================================================================
# Target rules for targets named upload_Tetris

# Build rule for target.
upload_Tetris: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upload_Tetris
.PHONY : upload_Tetris

# fast build rule for target.
upload_Tetris/fast:
	$(MAKE) -f CMakeFiles/upload_Tetris.dir/build.make CMakeFiles/upload_Tetris.dir/build
.PHONY : upload_Tetris/fast

#=============================================================================
# Target rules for targets named upload_eeprom

# Build rule for target.
upload_eeprom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upload_eeprom
.PHONY : upload_eeprom

# fast build rule for target.
upload_eeprom/fast:
	$(MAKE) -f CMakeFiles/upload_eeprom.dir/build.make CMakeFiles/upload_eeprom.dir/build
.PHONY : upload_eeprom/fast

#=============================================================================
# Target rules for targets named Tetris

# Build rule for target.
Tetris: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Tetris
.PHONY : Tetris

# fast build rule for target.
Tetris/fast:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/build
.PHONY : Tetris/fast

#=============================================================================
# Target rules for targets named set_calibration

# Build rule for target.
set_calibration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 set_calibration
.PHONY : set_calibration

# fast build rule for target.
set_calibration/fast:
	$(MAKE) -f CMakeFiles/set_calibration.dir/build.make CMakeFiles/set_calibration.dir/build
.PHONY : set_calibration/fast

#=============================================================================
# Target rules for targets named get_status

# Build rule for target.
get_status: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_status
.PHONY : get_status

# fast build rule for target.
get_status/fast:
	$(MAKE) -f CMakeFiles/get_status.dir/build.make CMakeFiles/get_status.dir/build
.PHONY : get_status/fast

#=============================================================================
# Target rules for targets named get_fuses

# Build rule for target.
get_fuses: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_fuses
.PHONY : get_fuses

# fast build rule for target.
get_fuses/fast:
	$(MAKE) -f CMakeFiles/get_fuses.dir/build.make CMakeFiles/get_fuses.dir/build
.PHONY : get_fuses/fast

#=============================================================================
# Target rules for targets named disassemble_Tetris

# Build rule for target.
disassemble_Tetris: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 disassemble_Tetris
.PHONY : disassemble_Tetris

# fast build rule for target.
disassemble_Tetris/fast:
	$(MAKE) -f CMakeFiles/disassemble_Tetris.dir/build.make CMakeFiles/disassemble_Tetris.dir/build
.PHONY : disassemble_Tetris/fast

#=============================================================================
# Target rules for targets named set_fuses

# Build rule for target.
set_fuses: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 set_fuses
.PHONY : set_fuses

# fast build rule for target.
set_fuses/fast:
	$(MAKE) -f CMakeFiles/set_fuses.dir/build.make CMakeFiles/set_fuses.dir/build
.PHONY : set_fuses/fast

ATmega-master/spi.obj: ATmega-master/spi.cpp.obj

.PHONY : ATmega-master/spi.obj

# target to build an object file
ATmega-master/spi.cpp.obj:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/ATmega-master/spi.cpp.obj
.PHONY : ATmega-master/spi.cpp.obj

ATmega-master/spi.i: ATmega-master/spi.cpp.i

.PHONY : ATmega-master/spi.i

# target to preprocess a source file
ATmega-master/spi.cpp.i:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/ATmega-master/spi.cpp.i
.PHONY : ATmega-master/spi.cpp.i

ATmega-master/spi.s: ATmega-master/spi.cpp.s

.PHONY : ATmega-master/spi.s

# target to generate assembly for a file
ATmega-master/spi.cpp.s:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/ATmega-master/spi.cpp.s
.PHONY : ATmega-master/spi.cpp.s

display.obj: display.cpp.obj

.PHONY : display.obj

# target to build an object file
display.cpp.obj:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/display.cpp.obj
.PHONY : display.cpp.obj

display.i: display.cpp.i

.PHONY : display.i

# target to preprocess a source file
display.cpp.i:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/display.cpp.i
.PHONY : display.cpp.i

display.s: display.cpp.s

.PHONY : display.s

# target to generate assembly for a file
display.cpp.s:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/display.cpp.s
.PHONY : display.cpp.s

game.obj: game.cpp.obj

.PHONY : game.obj

# target to build an object file
game.cpp.obj:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/game.cpp.obj
.PHONY : game.cpp.obj

game.i: game.cpp.i

.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s

.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/game.cpp.s
.PHONY : game.cpp.s

game_sm.obj: game_sm.cpp.obj

.PHONY : game_sm.obj

# target to build an object file
game_sm.cpp.obj:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/game_sm.cpp.obj
.PHONY : game_sm.cpp.obj

game_sm.i: game_sm.cpp.i

.PHONY : game_sm.i

# target to preprocess a source file
game_sm.cpp.i:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/game_sm.cpp.i
.PHONY : game_sm.cpp.i

game_sm.s: game_sm.cpp.s

.PHONY : game_sm.s

# target to generate assembly for a file
game_sm.cpp.s:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/game_sm.cpp.s
.PHONY : game_sm.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/main.cpp.s
.PHONY : main.cpp.s

matrixdisplay.obj: matrixdisplay.cpp.obj

.PHONY : matrixdisplay.obj

# target to build an object file
matrixdisplay.cpp.obj:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/matrixdisplay.cpp.obj
.PHONY : matrixdisplay.cpp.obj

matrixdisplay.i: matrixdisplay.cpp.i

.PHONY : matrixdisplay.i

# target to preprocess a source file
matrixdisplay.cpp.i:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/matrixdisplay.cpp.i
.PHONY : matrixdisplay.cpp.i

matrixdisplay.s: matrixdisplay.cpp.s

.PHONY : matrixdisplay.s

# target to generate assembly for a file
matrixdisplay.cpp.s:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/matrixdisplay.cpp.s
.PHONY : matrixdisplay.cpp.s

tetromino.obj: tetromino.cpp.obj

.PHONY : tetromino.obj

# target to build an object file
tetromino.cpp.obj:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/tetromino.cpp.obj
.PHONY : tetromino.cpp.obj

tetromino.i: tetromino.cpp.i

.PHONY : tetromino.i

# target to preprocess a source file
tetromino.cpp.i:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/tetromino.cpp.i
.PHONY : tetromino.cpp.i

tetromino.s: tetromino.cpp.s

.PHONY : tetromino.s

# target to generate assembly for a file
tetromino.cpp.s:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/tetromino.cpp.s
.PHONY : tetromino.cpp.s

timing.obj: timing.c.obj

.PHONY : timing.obj

# target to build an object file
timing.c.obj:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/timing.c.obj
.PHONY : timing.c.obj

timing.i: timing.c.i

.PHONY : timing.i

# target to preprocess a source file
timing.c.i:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/timing.c.i
.PHONY : timing.c.i

timing.s: timing.c.s

.PHONY : timing.s

# target to generate assembly for a file
timing.c.s:
	$(MAKE) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/timing.c.s
.PHONY : timing.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... get_calibration"
	@echo "... upload_Tetris"
	@echo "... upload_eeprom"
	@echo "... edit_cache"
	@echo "... Tetris"
	@echo "... rebuild_cache"
	@echo "... set_calibration"
	@echo "... get_status"
	@echo "... get_fuses"
	@echo "... disassemble_Tetris"
	@echo "... set_fuses"
	@echo "... ATmega-master/spi.obj"
	@echo "... ATmega-master/spi.i"
	@echo "... ATmega-master/spi.s"
	@echo "... display.obj"
	@echo "... display.i"
	@echo "... display.s"
	@echo "... game.obj"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... game_sm.obj"
	@echo "... game_sm.i"
	@echo "... game_sm.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... matrixdisplay.obj"
	@echo "... matrixdisplay.i"
	@echo "... matrixdisplay.s"
	@echo "... tetromino.obj"
	@echo "... tetromino.i"
	@echo "... tetromino.s"
	@echo "... timing.obj"
	@echo "... timing.i"
	@echo "... timing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

